@extends('layouts.app') @section('css')
<link
    rel="stylesheet"
    href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css"
/>
<link
    rel="stylesheet"
    href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css"
/>
<link
    rel="stylesheet"
    href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css"
/>
<script>
    function make_script(link) {
        let script = document.createElement("script");
        script.src = link;
        document.body.appendChild(script);
    }

    window.onload = () => {
        make_script(
            "http://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"
        );

        setTimeout(() => {
            make_script(
                "https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"
            );
            make_script(
                "https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"
            );
            make_script(
                "https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"
            );
            make_script(
                "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"
            );
            make_script(
                "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"
            );            
            make_script(
                "https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"
            );
            make_script(
                "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"
            );
            make_script(
                "https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"
            );
        }, 100);

        setTimeout(() => {
            if (!$.fn.DataTable.isDataTable("#myTable")) {
                $("#myTable").dataTable({
                    responsive: true,
                    dom: "Bfrtip",
                    buttons: ["copy", "csv", "excel", "pdf", "print"]                   
                });
            }
        }, 2000);
    };
</script>
@endsection @section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="text-right">
                <h5>Report: {{$customer->name}}</h5>
                <p>
                    {{$customer->mobile}} <br />
                    {{$customer->address}} <br />
                    ID: {{$customer->identification}}
                </p>
            </div>
            <div class="table-responsive">
                <table class="table" id="myTable">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Country</th>
                            <th>Sender</th>
                            <th>Reference</th>
                            <th>Payment Date</th>
                            <th>Amount</th>
                            <th>Incentive</th>
                            <th>Incentive Paid</th>
                            <th>Paid By</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($customer->Remitance as $remitance)
                        <tr>
                            <td>{{$loop->index+1}}</td>
                            <td>{{$remitance->sending_country}}</td>
                            <td>{{$remitance->sender}}</td>
                            <td>#{{$remitance->reference}}</td>
                            <td>{{$remitance->payment_date}}</td>
                            <td>{{number_format($remitance->amount, 2)}}</td>
                            <td>
                                {{number_format($remitance->incentive_amount, 2)}}
                            </td>
                            <td>{{$remitance->incentive_date}}</td>
                            <td>{{$remitance->payment_type}}</td>
                            <td>
                                {{number_format($remitance->amount + $remitance->incentive_amount, 2)}}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div style="position: fixed; bottom:0;">
                <p class="text-muted text-right">
                    Generated By: {{auth()->user()->name}} |
                    {{ date("D d-M-Y ") }}
                </p>
            </div>
        </div>
    </div>
</div>
@endsection
