@extends('layouts.app') @section('css') @endsection @section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="text-right">
                <h5>Report: {{$customer->name}}</h5>
                <p>
                    {{$customer->mobile}} <br />
                    {{$customer->address}} <br />
                    ID: {{$customer->identification}}
                </p>
            </div>
            <b-table
                striped
                hover
                :items="{{$customer->Remitance}}"
                :fields="[{key:'id', label:'#'}, 'payment_date', 'sender', 'sending_country', 'exchange_house', 'remit_type', {key:'amount', sortable:true}, {key:'incentive_amount', label:'Incentive', sortable:true}, 'total']"
            >
                <template v-slot:cell(id)="row">
                    <p v-html="row.index + 1"></p>
                </template>
                <template v-slot:cell(total)="row">
                    <p v-html="row.item.amount + row.item.incentive_amount"></p>
                </template>
            </b-table>

            <div style="position: fixed; bottom:0;">
                <p class="text-muted text-right">
                    Generated By: {{auth()->user()->name}} |
                    {{ date("D d-M-Y ") }}
                </p>
            </div>
        </div>
    </div>
</div>
@endsection
