@extends('layouts.app') @section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-2">
                    <img
                        src="{{ asset('image/logo.png') }}"
                        alt="logo"
                        class="img-fluid pl-5 pr-2"
                    />
                </div>
                <div class="col-md-10">
                    <h1>AGRANI BANK LIMITED</h1>
                    <h5>
                        JHALAM BAZAR BRANCH, CUMILLA MOB: 01819-412930,
                        01713-253464
                    </h5>
                </div>
            </div>
            <hr style="border: 1px solid var(--green); border-radius: 5px;" />
            <div class="text-center justify-content-center mt-5 p-2 col-6 offset-3">                
                <hr />
                <h3>Remitance Report {{ date("F-Y", $date) }}</h3>
                <div class="px-5">
                    <table class="table">
                        <tr>
                            <td>1</td>
                            <td class="text-left">SPOTCASH</td>
                            <td>{{number_format($spotcash, 2)}}</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td class="text-left">COC</td>
                            <td>{{number_format($coc, 2)}}</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td class="text-left">A/C Payee</td>
                            <td>{{number_format($acpay, 2)}}</td>
                        </tr>
                        <tr>                            
                            <td colspan="2"><b>Total</b></td>
                            <td><b>{{number_format($spotcash + $coc + $acpay, 2)}}</b></td>
                        </tr>
                        <tr>                            
                            <td colspan="2"></td>
                            <td><b class="text-danger">{{number_format($spotcash + $coc + $acpay, 2)}}</b></td>
                        </tr>
                    </table>
                </div>
                <hr>
            </div>
            <div class="display_print">
                <p class="text-muted text-right">
                    Generated By: {{auth()->user()->name}} |
                    {{ date("D d-M-Y ") }}
                </p>
            </div>
        </div>
    </div>
</div>
@endsection
